name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

defaults:
  run:
    shell: bash

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (Optional) Path to changelog.
          changelog: CHANGELOG.md
          # (Required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

  # upload-assets:
  #     runs-on: windows-latest
  #     steps:
  #       - uses: actions/checkout@v3
  #       - uses: taiki-e/upload-rust-binary-action@v1
  #         with:
  #           # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
  #           # Note that glob pattern is not supported yet.
  #           bin: gh-release-test
  #           # (required) GitHub token for uploading assets to GitHub Releases.
  #           token: ${{ secrets.GITHUB_TOKEN }}
  upload-assets:
    runs-on: windows-latest
    steps:
      - name: Compile code
        run: cargo build --release
      - uses: softprops/action-gh-release@v1
        with:
          files: target/release/time-for.exe